name: build

on:
  push:
    tags:
      - '**'

env:
  DOTNET_VERSION: '6.0.x' # The .NET SDK version to use
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  OUTPUT_NAME: COM3D2.DressCode

jobs:
  build:

    runs-on: windows-2019

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-quality: ga

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore --output build
      
    - name: Create the package
      run: |
        $archiveName = "$env:OUTPUT_NAME-$env:GITHUB_REF_NAME.zip"
        Add-Content -Value "ARCHIVE_NAME=$archiveName" -Path $env:GITHUB_ENV
        $basePath = Get-Location
        Set-Location src\build
        New-Item -Type Directory config, plugins
        Move-Item localization config
        Move-Item DressCode.dll, COM3D2.I2PluginLocalization.dll plugins
        Compress-Archive -Path config, plugins -DestinationPath $basePath\$archiveName -CompressionLevel NoCompression

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        fail_on_unmatched_files: true
        files: ${{ env.ARCHIVE_NAME }}
