name: build

on:
  push:
    tags:
      - '**'

env:
  DOTNET_VERSION: '6.0.x' # .NET SDK version
  DOTNET_CLI_TELEMETRY_OPTOUT: false
  ARCHIVE_PATH: ${{ github.workspace }}\${{ github.event.repository.name }}-${{ github.ref_name }}.zip

jobs:
  build:
    runs-on: windows-2022

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore --property:OutputPath=build

      - name: Create package
        run: |
          $assemblyName = dotnet msbuild -getProperty:AssemblyName src
          Set-Location src\build
          $pluginDirectory = "BepInEx\plugins\DressCode"
          New-Item -Type Directory $pluginDirectory
          Move-Item "$assemblyName.dll",localization $pluginDirectory
          Move-Item I2PluginLocalization.dll BepInEx\plugins
          Compress-Archive -DestinationPath $env:ARCHIVE_PATH -Path BepInEx

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: ${{ env.ARCHIVE_PATH }}
